name: run main.py

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every day at midnight UTC

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Check repo content
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Specify the Python version you need

    - name: Install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: execute py script
      run: python main.py  # Replace 'your_script.py' with your script's name