name: run main.py

on:
  schedule:
    - cron: '30 11 * * 5'  # Every Friday at 11:30 AM UTC (5 PM IST)

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Check repo content
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Specify the Python version you need

    - name: Install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: execute py script
      env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: python main.py  # Replace 'your_script.py' with your script's name
    
    # - name: Commit changes
    #   run: |
    #     git config --global user.name 'github-actions[bot]'
    #     git config --global user.email 'github-actions[bot]@users.noreply.github.com'
    #     git pull origin main
    #     git add "State Bank of India.xlsx"
    #     git commit -m 'Update Excel file with latest prices'
    #     git push origin main
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Check for changes
      id: check_changes
      run: |
        git add "State Bank of India.xlsx"
        git diff-index --quiet HEAD || echo "Changes detected"
        echo "::set-output name=changes::$(git diff-index --quiet HEAD || echo 'true')"

    - name: Commit and push changes
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git commit -m 'Update Excel file with latest prices'
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: No changes to commit
      if: steps.check_changes.outputs.changes != 'true'
      run: echo "No changes to commit."